### ISSUE TITLE
[Feature Suggestion] Have the Resources be Configured Items

### ISSUE THREAD

**Issue by GhostwheelX** [jessev14/resource-dice#6]
Could we have the option to configure the items below as actual items with effects? So for example, someone might find a d6 of magical crossbow bolts, which automatically add to attack/damage (which is already done) and rolls the die as part of the "item usage"?

**Comment by jessev14** [comment]
Hi there, I've looked over your all your suggestions (so far). They seem like good ideas.

I'm fairly sure everything you've outlined could be implemented, but this module was funded by a commission and I unfortunately don't have the means to develop modules in my free time.

If you'd like to implement the features yourself, I'd be happy to merge a pull request. Otherwise, if you would be interested in funding these features, feel free to reach out on Discord: `enso#0361`.
